name: Sugerir una función
description: Propón algo que te falta en Epigrapho.
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Gracias por compartir tu idea.
  - type: textarea
    id: problem
    attributes:
      label: ¿Qué problema tienes?
      description: Cuéntanos también cómo resolvería el problema esta idea y en qué caso la usarías.
      placeholder: p. ej. Cuando preparo una enseñanza siempre me cuesta...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: ¿Qué solución te gustaría ver en Epigrapho?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: ¿Qué alternativas has considerado?
  - type: textarea
    id: general
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto o captura de pantalla sobre la sugerencia.
