/*
This file is part of the Epigrapho project, a fork of Notesnook
(https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Turns data/*.vrs into a module, because the mapping has to run in the
// browser and in Electron's main process, where there is no data folder to
// read. Comments and the lines about deliberately omitted verses are dropped:
// the tables are the only part the mapping uses, and the files are 30 KB of
// which most is prose. Run it with `npm run build-versification` whenever a
// .vrs file changes; the result is committed.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const data = fileURLToPath(new URL("../data/", import.meta.url));
const out = fileURLToPath(
  new URL("../src/versification-data.ts", import.meta.url)
);

const sources: Record<string, string> = {};
for (const file of readdirSync(data).filter((name) => name.endsWith(".vrs"))) {
  const id = file.replace(/\.vrs$/, "");
  const kept = readFileSync(data + file, "utf8")
    .split(/\r?\n/)
    .filter((line) => line.startsWith("#!") || !/^\s*(#|-|$)/.test(line))
    .map((line) => line.trim());
  sources[id] = kept.join("\n");
  console.error(`${id}: ${kept.length} líneas`);
}

const header = readFileSync(out, "utf8").split("\n").slice(0, 19).join("\n");
writeFileSync(
  out,
  `${header}

// Generated by scripts/build-versification.ts from data/*.vrs. Do not edit.
// eng.vrs and org.vrs are SIL's, MIT licensed: see data/LICENSE.sil.txt.
export const VRS_SOURCES: Record<string, string> = ${JSON.stringify(
    sources,
    null,
    2
  )};
`
);
console.error(`escrito ${out}`);
