/*
This file is part of the Epigrapho project, a fork of Notesnook
(https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// A3 Paso 3.1: M'Cheyne's calendar (1842, public domain) as USFM readings.
// data/mcheyne.json is khornberg/readingplans' transcription (commit of
// 2026-10-02, sha256 6167c96c…); a list of chapters is a fact, and the check
// below proves the transcription against the plan's own promise before a
// single day is written.
import { readFileSync, writeFileSync } from "node:fs";
import { chapterCounts } from "../src/reading-plans.ts";

const NAMES: Record<string, string> = {
  Genesis: "GEN",
  Exodus: "EXO",
  Leviticus: "LEV",
  Numbers: "NUM",
  Deuteronomy: "DEU",
  Joshua: "JOS",
  Judges: "JDG",
  Ruth: "RUT",
  "1Samuel": "1SA",
  "2Samuel": "2SA",
  "1Kings": "1KI",
  "2Kings": "2KI",
  "1Chronicles": "1CH",
  "2Chronicles": "2CH",
  Ezra: "EZR",
  Nehemiah: "NEH",
  Esther: "EST",
  Job: "JOB",
  Psalm: "PSA",
  Proverbs: "PRO",
  Ecclesiastes: "ECC",
  SongOfSongs: "SNG",
  Isaiah: "ISA",
  Jeremiah: "JER",
  Lamentations: "LAM",
  Ezekiel: "EZK",
  Daniel: "DAN",
  Hosea: "HOS",
  Joel: "JOL",
  Amos: "AMO",
  Obadiah: "OBA",
  Jonah: "JON",
  Micah: "MIC",
  Nahum: "NAM",
  Habakkuk: "HAB",
  Zephaniah: "ZEP",
  Haggai: "HAG",
  Zechariah: "ZEC",
  Malachi: "MAL",
  Matthew: "MAT",
  Mark: "MRK",
  Luke: "LUK",
  John: "JHN",
  Acts: "ACT",
  Romans: "ROM",
  "1Corinthians": "1CO",
  "2Corinthians": "2CO",
  Galatians: "GAL",
  Ephesians: "EPH",
  Philippians: "PHP",
  Colossians: "COL",
  "1 Thes": "1TH",
  "2 Thes": "2TH",
  "1Timothy": "1TI",
  "2Timothy": "2TI",
  Titus: "TIT",
  Philemon: "PHM",
  Hebrews: "HEB",
  James: "JAS",
  "1Peter": "1PE",
  "2Peter": "2PE",
  "1John": "1JN",
  "2John": "2JN",
  "3John": "3JN",
  Jude: "JUD",
  Revelation: "REV"
};

/** "Genesis 9-10" → "GEN.9-10"; "Psalm 119:1-24" → "PSA.119.1-24". */
export function toReading(text: string) {
  const match = /^(.+?) (\d+)(?::(\d+)-(\d+)|-(\d+))?$/.exec(text.trim());
  const book = match && NAMES[match[1]];
  if (!match || !book) throw new Error(`No es una lectura: ${text}`);
  const [, , chapter, from, to, lastChapter] = match;
  if (from) return `${book}.${chapter}.${from}-${to}`;
  return lastChapter
    ? `${book}.${chapter}-${lastChapter}`
    : `${book}.${chapter}`;
}

/** Every chapter a reading touches, as "BOOK.C". */
export function chaptersOf(reading: string) {
  const [book, rest] = [reading.slice(0, 3), reading.slice(4)];
  const range = /^(\d+)-(\d+)$/.exec(rest);
  if (range) {
    const out: string[] = [];
    for (let c = Number(range[1]); c <= Number(range[2]); c++)
      out.push(`${book}.${c}`);
    return out;
  }
  return [`${book}.${rest.split(".")[0]}`];
}

if (process.argv[1]?.endsWith("build-reading-plans.ts")) {
  const counts = chapterCounts();
  const source = JSON.parse(
    readFileSync(new URL("../data/mcheyne.json", import.meta.url), "utf8")
  ) as { data2: string[][] };
  const days = source.data2.map((day) => day.map(toReading));

  // The promise of the plan: the Old Testament once, the New Testament and
  // the Psalms twice. Psalm 119 and two other long chapters are read in parts,
  // so a chapter counts once per day it is touched.
  const read = new Map<string, number>();
  for (const day of days) {
    const touched = new Set(day.flatMap(chaptersOf));
    for (const chapter of touched)
      read.set(chapter, (read.get(chapter) ?? 0) + 1);
  }
  const NT = [...counts.keys()].indexOf("MAT");
  const problems: string[] = [];
  [...counts].forEach(([book, total], index) => {
    const twice = index >= NT || book === "PSA";
    for (let c = 1; c <= total; c++) {
      const times = read.get(`${book}.${c}`) ?? 0;
      const expected = twice ? 2 : 1;
      // A chapter read in parts is touched on each of its days.
      if (times < expected)
        problems.push(`${book}.${c}: ${times} de ${expected}`);
    }
  });
  if (days.length !== 365 || problems.length)
    throw new Error(
      `M'Cheyne no cuadra: ${days.length} días; ${problems.join(", ")}`
    );

  writeFileSync(
    new URL("../src/mcheyne-data.ts", import.meta.url),
    `// Generated by scripts/build-reading-plans.ts from data/mcheyne.json. Do not edit.\n` +
      `// M'Cheyne's calendar (1842), public domain: 365 days, four readings each.\n` +
      `export const MCHEYNE: string[][] = ${JSON.stringify(days)};\n`
  );
  console.log(`M'Cheyne: ${days.length} días, cobertura completa.`);
}
