/*
This file is part of the Notesnook project (https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Epigrapho: downloads the community themes that ship with the app and gives
// each one its own name. The original name, authors and license stay in the
// file, because the licenses ask for the credit. Pinned to one commit so
// running it again gives the same files.
//
//   node scripts/community-themes.mjs

import { mkdir, readdir, rm, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const REPO = "streetwriters/notesnook-themes";
const COMMIT = "ec0b47e6a374356f5e49e905f7a948a609839de0";

// [new id, new name, original id], light ones first, in the order Appearance
// lists them.
const THEMES = [
  ["papiro", "Papiro", "arborleaf"],
  ["cuarzo", "Cuarzo", "catppuccin-latte-mauve"],
  ["marmol", "Mármol", "cloud"],
  ["pergamino", "Pergamino", "flexoki-light-blue"],
  ["malaquita", "Malaquita", "kale"],
  ["alabastro", "Alabastro", "moonstone"],
  ["vitela", "Vitela", "mystic-dawn"],
  ["yeso", "Yeso", "proton-snow"],
  ["pizarra", "Pizarra", "slate-stone"],
  ["bermellon", "Bermellón", "tiniri-light"],
  ["sepia", "Sepia", "caramel-macchiato"],
  ["amatista", "Amatista", "catppuccin-mocha-mauve"],
  ["jacinto", "Jacinto", "dracula"],
  ["jaspe", "Jaspe", "everforest-dark"],
  ["tinta", "Tinta", "flexoki-dark"],
  ["ocre", "Ocre", "gruvbox-dark"],
  ["indigo", "Índigo", "kanagawa-dark"],
  ["plomo", "Plomo", "nord"],
  ["granate", "Granate", "rose-pine-rose"],
  ["zafiro", "Zafiro", "tokyonight-moon"],
  ["onice", "Ónice", "default-pitch-black"]
];

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(
  __dirname,
  "..",
  "src",
  "theme-engine",
  "themes",
  "community"
);

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

for (const [id, name, original] of THEMES) {
  const url = `https://raw.githubusercontent.com/${REPO}/${COMMIT}/themes/${original}/v1/theme.json`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${original}: ${response.status}`);
  const theme = await response.json();
  delete theme.$schema;
  const out = {
    ...theme,
    id: `epigrapho-${id}`,
    name,
    basedOn: theme.name,
    description: `Based on ${theme.name}.`,
    homepage: `https://github.com/${REPO}/tree/${COMMIT}/themes/${original}`
  };
  await writeFile(
    path.join(OUT, `${id}.json`),
    JSON.stringify(out, null, 2) + "\n"
  );
}

const names = THEMES.map(([id]) => id);
const index = `/*
This file is part of the Notesnook project (https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by scripts/community-themes.mjs. Do not edit.
${names.map((n) => `import ${n} from "./${n}.json";`).join("\n")}

export default [
${names.map((n) => `  ${n}`).join(",\n")}
];
`;
await writeFile(path.join(OUT, "index.ts"), index);
console.log((await readdir(OUT)).length - 1, "themes");
