/*
This file is part of the Notesnook project (https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by scripts/community-themes.mjs. Do not edit.
import papiro from "./papiro.json";
import cuarzo from "./cuarzo.json";
import marmol from "./marmol.json";
import pergamino from "./pergamino.json";
import malaquita from "./malaquita.json";
import alabastro from "./alabastro.json";
import vitela from "./vitela.json";
import yeso from "./yeso.json";
import pizarra from "./pizarra.json";
import bermellon from "./bermellon.json";
import sepia from "./sepia.json";
import amatista from "./amatista.json";
import jacinto from "./jacinto.json";
import jaspe from "./jaspe.json";
import tinta from "./tinta.json";
import ocre from "./ocre.json";
import indigo from "./indigo.json";
import plomo from "./plomo.json";
import granate from "./granate.json";
import zafiro from "./zafiro.json";
import onice from "./onice.json";

export default [
  papiro,
  cuarzo,
  marmol,
  pergamino,
  malaquita,
  alabastro,
  vitela,
  yeso,
  pizarra,
  bermellon,
  sepia,
  amatista,
  jacinto,
  jaspe,
  tinta,
  ocre,
  indigo,
  plomo,
  granate,
  zafiro,
  onice
];
